spring.jpa.hibernate
spring.datasource.url=jdbc:mysql://localhost:3306/springbootregiandlogin
spring.datasource.username=root
spring.datasource.password=
spring.jpa.properties.hibernate.format_sql=true